// src/cms/analytics/widgetDefs.js
// Central widget catalogue. Every widget is defined once here.

export const WIDGET_SECTIONS = ["Overview", "Activity", "Content", "Learners", "Segmentation"];

export const WIDGET_DEFS = [
  // ── Overview ──────────────────────────────────────────────────────────────
  {
    id: "w_total_users",
    label: "Total Users",
    section: "Overview",
    description: "All registered accounts",
    preview: "kpi",
    accent: "#E85F00",
    info: "Total number of registered accounts, regardless of verification or activity status.",
    defaultSize: "sm",
  },
  {
    id: "w_dau",
    label: "Daily Active",
    section: "Overview",
    description: "Active in the last 24h",
    preview: "kpi",
    accent: "#10B981",
    info: "Users who have been active (last_active_at) in the past 24 hours.",
    defaultSize: "sm",
  },
  {
    id: "w_wau",
    label: "Weekly Active",
    section: "Overview",
    description: "Active in the last 7 days",
    preview: "kpi",
    accent: "#0EA5E9",
    info: "Unique users active in the last 7 days.",
    defaultSize: "sm",
  },
  {
    id: "w_mau",
    label: "Monthly Active",
    section: "Overview",
    description: "Active in the last 30 days",
    preview: "kpi",
    accent: "#8B5CF6",
    info: "Unique users active in the last 30 days.",
    defaultSize: "sm",
  },
  {
    id: "w_new_30d",
    label: "New (30 days)",
    section: "Overview",
    description: "Sign-ups in the past month",
    preview: "kpi",
    accent: "#F59E0B",
    info: "New accounts created in the last 30 days.",
    defaultSize: "sm",
  },
  {
    id: "w_premium",
    label: "Premium Users",
    section: "Overview",
    description: "Users with premium access",
    preview: "kpi",
    accent: "#6366F1",
    info: "Count of users with is_premium = true.",
    defaultSize: "sm",
  },

  // ── Activity ──────────────────────────────────────────────────────────────
  {
    id: "w_signups_trend",
    label: "New Sign-ups",
    section: "Activity",
    description: "Daily new users over 30 days",
    preview: "area",
    accent: "#E85F00",
    info: "Daily count of new user registrations over the past 30 days.",
    defaultSize: "md",
  },
  {
    id: "w_dau_trend",
    label: "Active Users Trend",
    section: "Activity",
    description: "Daily active users over 30 days",
    preview: "area",
    accent: "#10B981",
    info: "How many users were active each day over the past 30 days.",
    defaultSize: "md",
  },
  {
    id: "w_lessons_trend",
    label: "Lessons Completed",
    section: "Activity",
    description: "Daily lesson completions over 30 days",
    preview: "bars",
    accent: "#F59E0B",
    info: "Number of lessons completed per day over the past 30 days.",
    defaultSize: "md",
  },
  {
    id: "w_exercises_trend",
    label: "Exercise Attempts",
    section: "Activity",
    description: "Daily exercise attempts over 30 days",
    preview: "bars",
    accent: "#EF4444",
    info: "Total exercise attempts per day over the past 30 days.",
    defaultSize: "md",
  },

  // ── Content ───────────────────────────────────────────────────────────────
  {
    id: "w_top_lessons",
    label: "Top Lessons",
    section: "Content",
    description: "Most completed lessons",
    preview: "bars",
    accent: "#E85F00",
    info: "Top 10 lessons ranked by total completion count.",
    defaultSize: "lg",
  },
  {
    id: "w_chapter_progress",
    label: "Chapter Reach",
    section: "Content",
    description: "Unique learners per chapter",
    preview: "bars",
    accent: "#10B981",
    info: "How many unique learners have completed at least one lesson in each chapter.",
    defaultSize: "lg",
  },

  // ── Learners ──────────────────────────────────────────────────────────────
  {
    id: "w_onboarding_funnel",
    label: "Onboarding Funnel",
    section: "Learners",
    description: "Sign-up → verified → onboarded",
    preview: "bars",
    accent: "#E85F00",
    info: "Drop-off at each stage: registered, email-verified, onboarded, completed onboarding flow.",
    defaultSize: "lg",
  },
  {
    id: "w_churn_health",
    label: "Engagement Health",
    section: "Learners",
    description: "Active vs at-risk vs churned",
    preview: "donut",
    accent: "#10B981",
    info: "Active (7d), at-risk (8–30d), churned (30d+), never active.",
    defaultSize: "md",
  },
  {
    id: "w_streak_dist",
    label: "Streak Distribution",
    section: "Learners",
    description: "Users grouped by streak length",
    preview: "bars",
    accent: "#F59E0B",
    info: "How many users fall into each streak-length bucket: 0, 1–3, 4–7, 8–14, 15–30, 30+.",
    defaultSize: "md",
  },

  // ── Segmentation ──────────────────────────────────────────────────────────
  {
    id: "w_voice_dist",
    label: "Voice Preference",
    section: "Segmentation",
    description: "Male / Female / Mix distribution",
    preview: "donut",
    accent: "#8B5CF6",
    info: "How learners chose their TTS voice during onboarding.",
    defaultSize: "sm",
  },
  {
    id: "w_knowledge_dist",
    label: "Knowledge Level",
    section: "Segmentation",
    description: "Self-reported level at sign-up",
    preview: "donut",
    accent: "#0EA5E9",
    info: "Distribution of self-reported Armenian knowledge level from onboarding.",
    defaultSize: "sm",
  },
  {
    id: "w_country_dist",
    label: "Top Countries",
    section: "Segmentation",
    description: "Learner locations",
    preview: "bars",
    accent: "#10B981",
    info: "Top 12 countries by onboarded user count.",
    defaultSize: "md",
  },
  {
    id: "w_goal_dist",
    label: "Daily Goal",
    section: "Segmentation",
    description: "Minutes per day chosen at sign-up",
    preview: "bars",
    accent: "#F59E0B",
    info: "Distribution of daily study-goal choices (in minutes) from onboarding.",
    defaultSize: "sm",
  },
  {
    id: "w_auth_methods",
    label: "Sign-in Methods",
    section: "Segmentation",
    description: "Password / Google / Telegram split",
    preview: "donut",
    accent: "#6366F1",
    info: "How users authenticate: password-only, Google, Telegram, or both OAuth providers.",
    defaultSize: "sm",
  },
];

export const WIDGET_MAP = Object.fromEntries(WIDGET_DEFS.map((w) => [w.id, w]));

// Widgets that are capped at certain sizes (never allowed at larger sizes)
export const WIDGET_SIZE_CAPS = {
  w_total_users: ["sm", "md"],
  w_dau:         ["sm", "md"],
  w_wau:         ["sm", "md"],
  w_mau:         ["sm", "md"],
  w_new_30d:     ["sm", "md"],
  w_premium:     ["sm", "md"],
  w_voice_dist:  ["sm", "md"],
  w_knowledge_dist: ["sm", "md"],
  w_goal_dist:   ["sm", "md"],
  w_auth_methods: ["sm", "md"],
};

export const ALL_SIZES = ["sm", "md", "lg"];
